# Generated by Django 4.1.13 on 2024-01-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_alter_taskinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'ordering': ['task_created'], 'verbose_name_plural': 'TaskInfo'},
        ),
    ]
